package slproject;

import java.awt.HeadlessException;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nimbus
 */
public class start_page extends javax.swing.JFrame {

    /**
     * Creates new form start_page
     */
    public start_page() {
        initComponents();

        try {
            Image i = ImageIO.read(getClass().getResource("sls_logo.png"));
            setIconImage(i);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (Config.currentUserRole.equalsIgnoreCase("Admin") || Config.currentUserRole.equalsIgnoreCase("Manager")) {
            btnAddPurchase.setEnabled(true);
            btnEditPurchase.setEnabled(true);
            btnAllotAllotment.setEnabled(true);
            btnAddUser.setEnabled(true);
            btnAddInv.setEnabled(true);
            btnAddOffice.setEnabled(true);
            btnDBBackup.setEnabled(true);

        } else {
            btnAddPurchase.setEnabled(false);
            btnEditPurchase.setEnabled(false);
            btnAllotAllotment.setEnabled(false);
            btnAddUser.setEnabled(false);
            btnAddInv.setEnabled(false);
            btnAddOffice.setEnabled(false);
            btnDBBackup.setEnabled(false);

        }
        //  setExtendedState(MAXIMIZED_BOTH);
        //  setLayout(new GridLayout(1,1,2,2));

        this.setTitle(Config.PRODUCTTITLE + "_" + Config.VERSION + " - Home (Current User : " + Config.currentUserFullName + ")");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnDBBackup = new javax.swing.JButton();
        pnlPurchase = new javax.swing.JPanel();
        btnViewPurchase = new javax.swing.JButton();
        btnAddPurchase = new javax.swing.JButton();
        btnEditPurchase = new javax.swing.JButton();
        pnlAllotment = new javax.swing.JPanel();
        btnViewAllotment = new javax.swing.JButton();
        btnAllotAllotment = new javax.swing.JButton();
        pnlBreakdown = new javax.swing.JPanel();
        btnViewBreakdown = new javax.swing.JButton();
        pnlUsers = new javax.swing.JPanel();
        btnViewUser = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        pnlInventory = new javax.swing.JPanel();
        btnViewInv = new javax.swing.JButton();
        btnAddInv = new javax.swing.JButton();
        pnlOffice = new javax.swing.JPanel();
        btnViewOffice = new javax.swing.JButton();
        btnAddOffice = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select user", "Admin", "Srmanager", "manager" }));

        button1.setLabel("view");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button2.setLabel("allot");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        label1.setText("Purchase");

        label2.setText("Allotment");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("schoolsLENS Inventory System");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("schoolsLENS Inventory System");

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("Click to logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnDBBackup.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDBBackup.setText("DB Backup");
        btnDBBackup.setToolTipText("Click to backup database");
        btnDBBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDBBackupActionPerformed(evt);
            }
        });

        pnlPurchase.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purchase", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N
        pnlPurchase.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N

        btnViewPurchase.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnViewPurchase.setText("View");
        btnViewPurchase.setToolTipText("Click to view product list");
        btnViewPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPurchaseActionPerformed(evt);
            }
        });

        btnAddPurchase.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAddPurchase.setText("Add");
        btnAddPurchase.setToolTipText("Click to add product");
        btnAddPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPurchaseActionPerformed(evt);
            }
        });

        btnEditPurchase.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEditPurchase.setText("Edit");
        btnEditPurchase.setToolTipText("Click to edit product");
        btnEditPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPurchaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPurchaseLayout = new javax.swing.GroupLayout(pnlPurchase);
        pnlPurchase.setLayout(pnlPurchaseLayout);
        pnlPurchaseLayout.setHorizontalGroup(
            pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPurchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlPurchaseLayout.setVerticalGroup(
            pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPurchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAllotment.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Allotment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N

        btnViewAllotment.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnViewAllotment.setText("View");
        btnViewAllotment.setToolTipText("Click to view alloted product list");
        btnViewAllotment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllotmentActionPerformed(evt);
            }
        });

        btnAllotAllotment.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAllotAllotment.setText("Allot");
        btnAllotAllotment.setToolTipText("Click to allot product");
        btnAllotAllotment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllotAllotmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAllotmentLayout = new javax.swing.GroupLayout(pnlAllotment);
        pnlAllotment.setLayout(pnlAllotmentLayout);
        pnlAllotmentLayout.setHorizontalGroup(
            pnlAllotmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllotmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAllotAllotment, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewAllotment, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAllotmentLayout.setVerticalGroup(
            pnlAllotmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllotmentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAllotmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAllotAllotment, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAllotment, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBreakdown.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Breakdown-Repaired", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N

        btnViewBreakdown.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnViewBreakdown.setText("View");
        btnViewBreakdown.setToolTipText("Click to view breakdown-repaired product list");
        btnViewBreakdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBreakdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBreakdownLayout = new javax.swing.GroupLayout(pnlBreakdown);
        pnlBreakdown.setLayout(pnlBreakdownLayout);
        pnlBreakdownLayout.setHorizontalGroup(
            pnlBreakdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBreakdownLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewBreakdown, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnlBreakdownLayout.setVerticalGroup(
            pnlBreakdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBreakdownLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewBreakdown, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pnlUsers.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Users", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N

        btnViewUser.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnViewUser.setText("View");
        btnViewUser.setToolTipText("Click to view user list");
        btnViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUserActionPerformed(evt);
            }
        });

        btnAddUser.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAddUser.setText("Add");
        btnAddUser.setToolTipText("Click to add user");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUsersLayout = new javax.swing.GroupLayout(pnlUsers);
        pnlUsers.setLayout(pnlUsersLayout);
        pnlUsersLayout.setHorizontalGroup(
            pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUsersLayout.setVerticalGroup(
            pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlInventory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N

        btnViewInv.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnViewInv.setText("View");
        btnViewInv.setToolTipText("Click to view inventory list");
        btnViewInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInvActionPerformed(evt);
            }
        });

        btnAddInv.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAddInv.setText("Add");
        btnAddInv.setToolTipText("Click to add inventory");
        btnAddInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInventoryLayout = new javax.swing.GroupLayout(pnlInventory);
        pnlInventory.setLayout(pnlInventoryLayout);
        pnlInventoryLayout.setHorizontalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddInv, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewInv, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlInventoryLayout.setVerticalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddInv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewInv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlOffice.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Office", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N

        btnViewOffice.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnViewOffice.setText("View");
        btnViewOffice.setToolTipText("Cliick to view office list");
        btnViewOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewOfficeActionPerformed(evt);
            }
        });

        btnAddOffice.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAddOffice.setText("Add");
        btnAddOffice.setToolTipText("Click to add office");
        btnAddOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOfficeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOfficeLayout = new javax.swing.GroupLayout(pnlOffice);
        pnlOffice.setLayout(pnlOfficeLayout);
        pnlOfficeLayout.setHorizontalGroup(
            pnlOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOfficeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOfficeLayout.setVerticalGroup(
            pnlOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOfficeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDBBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pnlInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnlUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(pnlBreakdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53))
                                    .addComponent(pnlOffice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pnlPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlAllotment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAllotment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPurchase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBreakdown, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDBBackup, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPurchaseActionPerformed
        // TODO add your handling code here:

        Show_input show = new Show_input();
        //  input_trial input = new input_trial();
        show.setVisible(true);
        dispose();


    }//GEN-LAST:event_btnViewPurchaseActionPerformed


    private void btnAddPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPurchaseActionPerformed
        if (Config.currentUserRole.equalsIgnoreCase("Admin") || Config.currentUserRole.equalsIgnoreCase("Manager")) {
            input_trial input = new input_trial();
            input.setVisible(true);
            dispose();
        } else {
            input_trial input = new input_trial();
            input.setVisible(false);
            dispose();
            //  String warning="username is not valid";
            //  JOptionPane.showMessageDialog(null,warning);
            btnAddPurchase.setEnabled(false);
        }
    }//GEN-LAST:event_btnAddPurchaseActionPerformed

    private void btnEditPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPurchaseActionPerformed
        // TODO add your handling code here:
        if (Config.currentUserRole.equalsIgnoreCase("Admin") || Config.currentUserRole.equalsIgnoreCase("Manager")) {
            edit_table edit = new edit_table();
            edit.setVisible(true);
            dispose();

        } else {
//         edit_table edit = new edit_table();
//        edit.setVisible(false);
//        dispose();
            String warning = "username is not valid";
            JOptionPane.showMessageDialog(null, warning);

        }
    }//GEN-LAST:event_btnEditPurchaseActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        alot_search allot = new alot_search();
        allot.setVisible(true);
        dispose();
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        alot_search allot = new alot_search();
        allot.setVisible(true);
        dispose();
    }//GEN-LAST:event_button5ActionPerformed

    private void btnViewAllotmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllotmentActionPerformed
        // TODO add your handling code here:
        alot_search allot = new alot_search();
        allot.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewAllotmentActionPerformed

    private void btnAllotAllotmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllotAllotmentActionPerformed
        // TODO add your handling code here:
        allot_page allot = new allot_page();
        allot.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAllotAllotmentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Config.currentUserRole = null;

        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDBBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDBBackupActionPerformed
        try {
            File selectedFile = null;
            final JFileChooser fileDialog = new JFileChooser();
            fileDialog.setAcceptAllFileFilterUsed(false);
            fileDialog.addChoosableFileFilter(new FileNameExtensionFilter("SQL", "sql"));
            int returnVal = fileDialog.showSaveDialog(this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                selectedFile = fileDialog.getSelectedFile();
                System.out.println("selected file is" + selectedFile);

                if (selectedFile.getAbsolutePath().contains(".")) {
                    if (selectedFile.getAbsolutePath().endsWith(".sql")) {
                        backupSQL(Config.SCHEMANAME, selectedFile.getAbsolutePath());
                        JOptionPane.showMessageDialog(this, "Backup Successful","Backup successful",JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "You can export .sql file only","sql only",JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    selectedFile = new File(selectedFile.getAbsolutePath() + ".sql");
                    backupSQL("school", selectedFile.getAbsolutePath());
                    JOptionPane.showMessageDialog(this, "Backup Successful","Backup Successful",JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Exception",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDBBackupActionPerformed

    private void btnViewBreakdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBreakdownActionPerformed
        break_search breakdown = new break_search();
        breakdown.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewBreakdownActionPerformed

    private void btnViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUserActionPerformed
        // TODO add your handling code here:
        user_view view = new user_view();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewUserActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        user_add user = new user_add();
        user.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnViewInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInvActionPerformed
        // TODO add your handling code here:
        inventory_view view = new inventory_view();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewInvActionPerformed

    private void btnAddInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInvActionPerformed
        // TODO add your handling code here:
        inventory_add Add = new inventory_add();
        Add.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAddInvActionPerformed

    private void btnViewOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewOfficeActionPerformed
        // TODO add your handling code here:
        office_view View = new office_view();
        View.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnViewOfficeActionPerformed

    private void btnAddOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOfficeActionPerformed
        // TODO add your handling code here:
        office_add Add = new office_add();
        Add.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAddOfficeActionPerformed

    public static void backupSQL(String schemaName, String destPath) {
        try {
            // NOTE : Used to create a cmd command 
            String executeCmd = "cmd.exe /c \"" + getMySQLPath() + File.separator + "mysqldump\" "
                    + "-u root -proot --no-create-db " + schemaName + " > " + destPath;
            System.out.println("executing command : " + executeCmd + "\n\nPlease wait...");
            // NOTE : Executing the command here
            runCmd(executeCmd);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static String getMySQLPath() {
        String rv = "";
        try {// Truncate table data
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://" + Config.DBHOST + ":3306/" + Config.SCHEMANAME, Config.DBUSER, Config.DBPASS);
            Statement stmt = conn.createStatement();

            ResultSet rs = stmt.executeQuery("select @@basedir as basedir");

            while (rs.next()) {
                rv = rs.getString("basedir") + "bin";
            }

            conn.close();
            // Truncate table data
        } catch (Exception e) {
            // TODO: handle exception
        }
        return rv;
    }

    public static void runCmd(String command) {
        try {
            if (!command.startsWith("cmd.exe /c ")) {
                command = "cmd.exe /c " + command;
            }

            Process runtimeProcess = Runtime.getRuntime().exec(command);

            BufferedReader reader = new BufferedReader(new InputStreamReader(runtimeProcess.getInputStream()));
            String line;
            while ((line = reader.readLine()) != null) {
                // Parse line for required info
                System.out.println(line);
            }
        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddInv;
    private javax.swing.JButton btnAddOffice;
    private javax.swing.JButton btnAddPurchase;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnAllotAllotment;
    private javax.swing.JButton btnDBBackup;
    private javax.swing.JButton btnEditPurchase;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewAllotment;
    private javax.swing.JButton btnViewBreakdown;
    private javax.swing.JButton btnViewInv;
    private javax.swing.JButton btnViewOffice;
    private javax.swing.JButton btnViewPurchase;
    private javax.swing.JButton btnViewUser;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JPanel pnlAllotment;
    private javax.swing.JPanel pnlBreakdown;
    private javax.swing.JPanel pnlInventory;
    private javax.swing.JPanel pnlOffice;
    private javax.swing.JPanel pnlPurchase;
    private javax.swing.JPanel pnlUsers;
    // End of variables declaration//GEN-END:variables
}
